---
title: "Exploratory Analysis"
author: "Daniel P. Hall Riggins, MD, MPH"
format: html
date: today
embed-resources: true
---

Load dependencies:

```{r}
library(targets)
library(tidyverse)
library(ggdist)
library(janitor)
library(gtsummary)

tar_load(asthmaster_mod)
```


```{r}
asthmaster_mod |> 
    select(Albuterol_Cont_Dose, AgeAtEncounter, Weight, Race, Ethnicity, Sex, CCC, PneumoniaDx, Ipratropium, Magnesium_order, PASS_Initial, RR_Initial, O2_Initial, FiO2_Initial) |> 
    tbl_summary(by = "Albuterol_Cont_Dose") |> 
    modify_header(label = "**Starting Dose of Continuous Albuterol**")
```

```{r}
asthmaster_mod |> 
    ggplot(aes(x = Year, y = Albuterol_Cont_Dose_Factor)) +
    stat_dotsinterval()
```

```{r}
df <- filter(asthmaster_mod, !is.na(Albuterol_Cont_Dose_Logit))

df$Albuterol_Cont_Dose_Factor
```


```{r}
model <- glm(Albuterol_Cont_Dose_Logit ~ Year, family = "binomial", data = df)

model
```


```{r}
parameters::parameters(model, exponentiate = TRUE)
```


```{r}
asthmaster_mod |> 
    ggplot(aes(x = Albuterol_Cont_Dose)) +
    stat_dotsinterval()
```


```{r}
asthmaster_mod |> 
    ggplot(aes(x = PASS_Initial, y = Albuterol_Cont_Dose)) +
    stat_dotsinterval()
```


```{r}
asthmaster_mod |> 
    ggplot(aes(x = PASSchange0_12, y = Albuterol_Cont_Dose)) +
    stat_dotsinterval()
```
```{r}
asthmaster_mod |> 
    ggplot(aes(x = Albuterol_Cont_avg_duration, y = Albuterol_Cont_Dose)) +
    stat_dotsinterval() +
    coord_cartesian(xlim = c(0, 5))
```
```{r}
asthmaster_mod |> 
    ggplot(aes(x = Hospital_LOS, y = Albuterol_Cont_Dose)) +
    stat_dotsinterval() +
    coord_cartesian(xlim = c(0, 10))
```

